### ISSUE TITLE
Request: Support for current Wordpress version

### ISSUE THREAD

**Issue by sunjam** [mario-nolte/nc2wp-bookmarks#1]
`Warning: This plugin has not been tested with your current version of WordPress.  It has not been updated for the last three major releases.`

Version: 1.3.2
Author: Mario Nolte
Last Updated: 2 years ago
Requires WordPress Version: 3.9.2 or higher
Compatible up to: 5.2.14

Thanks for the awesome app.  Haven't tested it yet since it hasn't seen an update in some time.  Curious on any issues with current Wordpress and Bookmarks app installs.

**Comment by mario-nolte** [comment]
Should be fixed with the current version. Since the filter functionality is not working well I will still not upload this version to the WP plugin repository.
